name: workflows project
run-name: ${{ github.actor }} is running Github Actions

on:
  push:
    branches: [master]

  pull_request:
    branches: [master, dev]

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [14.x, 16.x, 18.x]

    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install yarn
        run: npm install -g yarn

      - name: Install package
        run: yarn install

      - name: Test
        run: yarn test

  build:
    needs: test
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x, 16.x, 18.x]

    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install yarn
        run: npm install -g yarn

      - name: install package
        run: yarn install

      - name: Lint code
        run: yarn run lint

      - name: Build CSS
        run: yarn run build:tailwind

      - name: build project
        run: yarn run build
