name: workflows project
run-name: ${{ github.actor }} is running Github Actions
on: ["push"]
jobs:
  setup:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-node@v3
        with:
          node-version: "16"
      - run: npm install

  lint:
    needs: setup
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-node@v3
        with:
          node-version: "16"
      - name: lint code
        run: npm run lint

  build:
    needs: lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-node@v3
        with:
          node-version: "16"
      - name: lint code
        run: npm run build
